<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>SyncTogether</AssemblyName>
    <RootNamespace>SyncTogether.Plugin</RootNamespace>
    <Version>0.4.1</Version>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MediaBrowser.Common">
      <HintPath>../../vendor/emby-4.9.3.0/MediaBrowser.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MediaBrowser.Controller">
      <HintPath>../../vendor/emby-4.9.3.0/MediaBrowser.Controller.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MediaBrowser.Model">
      <HintPath>../../vendor/emby-4.9.3.0/MediaBrowser.Model.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Web/synctogether.html" />
    <EmbeddedResource Include="Web/synctogether.js" />
  </ItemGroup>
</Project>
